### ISSUE TITLE
[1.16.5] CopperPot doesn't keep it's meals

### ISSUE THREAD

**Issue by DaLumma** [davidjjung/copperpot#1]
When the Pot get's Broken it doesn't store the unpackaged meals like FD's cooking pot does.

**Comment by davidjjung** [comment]
Hiya! Sorry to say, but this is currently a feature, not a bug--the copper pot appears just a bit too shallow in stature to keep its inventory. Might change this in a future, however, as I do feel bad that it simply voids recipes that didn't get a container. Thank you for your patience!

**Comment by davidjjung** [comment]
hm, on second consideration, I'd like to make it possible for the pot to hold a smaller maximum amount of meals when broken, to compensate--maybe 16 or 32. No idea how to code this, but hopefully that strikes a decent middle ground!

**Comment by DaLumma** [comment]
Sounds good to me, I would've thought that it maybe gives you part of the ingredients back, but that sounds better.👍

**Comment by davidjjung** [comment]
It's been implemented! The pot now cooks up to a maximum of 16 items before stopping, and keeps that inventory once broken. Good times
