### ISSUE TITLE
Setting fizzy yogurt to slabfish_snack tag in environmental and then feeding a slabfish a fizzy yogurt to a slabfish crashes the game

### ISSUE THREAD

**Issue by thelegitdolt** [davidjjung/copperpot#13]
This is so ridiculously minor and would likely take a bloody long time to fix but it would be insane if you did lol, anyways just letting ya know in case this is your end. I'll e posting this in environmental's github too

https://cdn.discordapp.com/attachments/905649496455782411/907525976613851168/crash-2021-11-08_22.58.43-client.txt - crash report

https://cdn.discordapp.com/attachments/905649496455782411/907525934561775616/latest.log - latest.log

**Comment by davidjjung** [comment]
Your steadfast commitment to exploring everything this mod has to offer is genuinely inspiring, and I wish I had the mental capacity to fix these bugs and tinker around with your suggestions. Thanks for the report, I'll fix it as soon as I am able.

**Comment by thelegitdolt** [comment]
You shouldn't sell yourself short, i wouldn't have been able to do this kind of stuff if you didn't make such a good mod with so much cool stuff lmao

**Comment by thelegitdolt** [comment]
https://github.com/team-abnormals/environmental/issues/254 posted this on environmental and bagel said it was an issue on your end, just wanted to let you know lol
