### ISSUE TITLE
Fruitful

### ISSUE THREAD

**Issue by Luuuma** [davidjjung/copperpot#4]
Trying to run this mod with Fruitful tells me I need to use version 2.0.0 of Fruitful, which is an old version.

**Comment by davidjjung** [comment]
Hm--running Fruitful 2.1.0 with CopperPot doesn't seem to have any major issues on my end. I do know that the mods.toml file necessitates 2.0.0 or later, though I suppose I'll be updating that very shortly. Is it possible to share a screenshot of where the game starts yelling at you? Thanks!

**Comment by Luuuma** [comment]
![image](https://user-images.githubusercontent.com/85845431/121819645-28f8a580-cc86-11eb-8920-c052a8928d1a.png)
Here

**Comment by davidjjung** [comment]
So strange;; I can't replicate the bug. So sorry to continue being a hassle, but have you checked your mods folder to make sure you don't have any duplicates? Having both versions of fruitful might be doing something funky, for instance

**Comment by Luuuma** [comment]
I don't, this is pretty much a new install of everything. Though it was working before your update.
![image](https://user-images.githubusercontent.com/85845431/121820049-7d048980-cc88-11eb-89a9-ba1b43365ac6.png)
I downgraded Fruitful and got the same message.

**Comment by davidjjung** [comment]
If that ain't the darndest thing. Mind sending one last picture of your modlist? The jar is working with both versions on my end

**Comment by Luuuma** [comment]
idk how to send a proper written list, but here's the folder
![image](https://user-images.githubusercontent.com/85845431/121821811-4ed87700-cc93-11eb-8bc7-0eb0e42c7cea.png)

**Comment by davidjjung** [comment]
I really can't fathom why anything would've changed about Fruitful--it updated, sure, but nothing drastic has been altered from what I can see. I also haven't touched it with any code regarding spiced apple jam or pork sandwiches,, 

I'm uploading a hotfix that updates the Fruitful version asap, along with another tiny fix. If that doesn't do it, I really don't know what to say--I'll leave the issue up in that case just to see if anybody else can contribute, but I'd recommend just playing without this mod at that point. So so sorry about this!

**Comment by Luuuma** [comment]
It might be something else on my end, though I can't see what. It's a new installation without any of the edits I did to my last one which broke it.
I can always go back to the previous version of this mod, since I'm pretty sure it worked before.

Thanks for your time anyway :)

**Comment by Bobisnotap** [comment]
![image](https://user-images.githubusercontent.com/60948714/121822629-51b87500-cc5d-11eb-94f4-4fb3be45a291.png)
I appear to be facing a very similar issue in 1.1.1

**Comment by davidjjung** [comment]
I cry;; maybe I can gather something from the latest.log? Sorry in advance

**Comment by Bobisnotap** [comment]
[latest.log](https://github.com/davidjjung/copperpot/files/6644710/latest.log)
Sure, here's mine!

**Comment by davidjjung** [comment]
https://www.dropbox.com/s/wkcfzojncl6g974/copperpot-1.16.5-1.1.1.jar?dl=0 Hmmmngh,, can you download this draft, and see if it works? Holding out for a hero here

**Comment by Bobisnotap** [comment]
It works! No errors on my side.

**Comment by davidjjung** [comment]
i feel     peace
