### ISSUE TITLE
No Recipe For Royal Jelly

### ISSUE THREAD

**Issue by MindFaer** [davidjjung/copperpot#5]
The recipe currently makes 2 raw meringue instead, even with buzzier bees installed, data file for context
[royal_jelly.txt](https://github.com/davidjjung/copperpot/files/6644517/royal_jelly.txt)

**Comment by davidjjung** [comment]
Lordie, thought I fixed that. Thank you and please standby!

**Comment by davidjjung** [comment]
Done! Done, it's done, and so am I aha
