### ISSUE TITLE
Game Crash When Making Yucca fudge

### ISSUE THREAD

**Issue by CosmicParticl** [davidjjung/copperpot#8]
As requested, I've attached the crash log to this issue that I mentioned in the comment section. Both Atmospheric and Peculiars are installed in this instance along with copper pot.

[crash-2021-08-14_14.44.02-server.txt](https://github.com/davidjjung/copperpot/files/6988934/crash-2021-08-14_14.44.02-server.txt)

**Comment by davidjjung** [comment]
turns out it was just the result of 2+ stupid mistakes in the recipe json breaking the mod three ways to sunday. cheers!
